export default {
    Search: [
      {
        Title: 'The Lord of the Rings: The Return of the King',
        Year: '2003',
        imdbID: 'tt0167260',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SX300.jpg',
      },
      {
        Title: 'The Lion King',
        Year: '1994',
        imdbID: 'tt0110357',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg',
      },
      {
        Title: 'King Kong',
        Year: '2005',
        imdbID: 'tt0360717',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjYxYmRlZWYtMzAwNC00MDA1LWJjNTItOTBjMzlhNGMzYzk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
      },
      {
        Title: 'The Last King of Scotland',
        Year: '2006',
        imdbID: 'tt0455590',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjM1NTkxNjkzMl5BMl5BanBnXkFtZTgwNDgwMDAxMzE@._V1_SX300.jpg',
      },
      {
        Title: 'King Arthur',
        Year: '2004',
        imdbID: 'tt0349683',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4MTk1NjI0OV5BMl5BanBnXkFtZTcwNDQxOTUyMQ@@._V1_SX300.jpg',
      },
      {
        Title: 'The Scorpion King',
        Year: '2002',
        imdbID: 'tt0277296',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjkxNTAwNTQ0M15BMl5BanBnXkFtZTYwMTQwMjM3._V1_SX300.jpg',
      },
      {
        Title: 'King Arthur: Legend of the Sword',
        Year: '2017',
        imdbID: 'tt1972591',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3ODY3Njc5Ml5BMl5BanBnXkFtZTgwMjQ5NjM5MTI@._V1_SX300.jpg',
      },
      {
        Title: 'King Kong',
        Year: '1933',
        imdbID: 'tt0024216',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BODM0MTEyMjQxOF5BMl5BanBnXkFtZTgwNzYwNTk1MjE@._V1._CR8.883331298828125,6.5333404541015625,344,488_SY132_CR2,0,89,132_AL_.jpg_V1_SX300.jpg',
      },
      {
        Title: 'The Fisher King',
        Year: '1991',
        imdbID: 'tt0101889',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BOGZmMDM1NTQtMzc0Yi00ODRiLWJjYjQtMGRmYWRlOTY2ODMxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
      },
      {
        Title: 'The King of Queens',
        Year: '1998–2007',
        imdbID: 'tt0165581',
        Type: 'series',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTI4NzcwODk1M15BMl5BanBnXkFtZTYwNjkxNTc2._V1_SX300.jpg',
      },
    ],
    totalResults: '2664',
    Response: 'True',
};