export default {
    Search: [
      {
        Title: 'The King of Comedy',
        Year: '1982',
        imdbID: 'tt0085794',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTAyNDM0OGMtMmQ5OS00OGJiLTljMDUtY2Y1OTFlYmM2ZTk2XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
      },
      {
        Title: 'King Arthur: Legend of the Sword',
        Year: '2017',
        imdbID: 'tt1972591',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3ODY3Njc5Ml5BMl5BanBnXkFtZTgwMjQ5NjM5MTI@._V1_SX300.jpg',
      },
      {
        Title: 'The Lion King 2: Simba\'s Pride',
        Year: '1998',
        imdbID: 'tt0120131',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZTZlOGU3OTAtODY5NC00NGRlLWE5NmItY2JhYzk4OGY0ZTdkXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg',
      },
      {
        Title: 'In the Name of the King: A Dungeon Siege Tale',
        Year: '2007',
        imdbID: 'tt0460780',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4ODI0ODA1Ml5BMl5BanBnXkFtZTcwNzMzMjU1MQ@@._V1_SX300.jpg',
      },
      {
        Title: 'King of the Hill',
        Year: '1997–2010',
        imdbID: 'tt0118375',
        Type: 'series',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzI5ODk5MTMtMDE4OC00ZWM5LTg0MzYtNTJmZTY3OWY3NzEzXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
      },
      {
        Title: 'The Man Who Would Be King',
        Year: '1975',
        imdbID: 'tt0073341',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWQzYjBjZmQtZDFiOS00ZDQ1LWI4MDAtMDk1NGE1NDBhYjNhL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
      },
      {
        Title: 'Anna and the King',
        Year: '1999',
        imdbID: 'tt0166485',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjVlMWU0NjktNDkyOC00NzViLTg3Y2EtMTg0ZmY5N2FiNzgzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
      },
      {
        Title: 'The King of Kong: A Fistful of Quarters',
        Year: '2007',
        imdbID: 'tt0923752',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzIwMmIwNzEtODhhOS00ZjFjLWI1OGMtNjBiMDFkMTgzZTY2XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
      },
      {
        Title: 'A Hologram for the King',
        Year: '2016',
        imdbID: 'tt2980210',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2MzU1NTg4NV5BMl5BanBnXkFtZTgwNzQ5MjAzODE@._V1_SX300.jpg',
      },
      {
        Title: 'The Lion King 1 1/2',
        Year: '2004',
        imdbID: 'tt0318403',
        Type: 'movie',
        Poster: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZWVkY2IxNTUtYzIwNi00ZmYwLWE5YzEtMDYzNzE1NGM5MTZjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_SX300.jpg',
      },
    ],
    totalResults: '2665',
    Response: 'True',
  }