export const App = {
    MENU_ON: 'MENU_ON',
    MENU_OFF: 'MENU_OFF'
}
export const Auth = {
    AUTH_REQUEST_SIGNIN: 'AUTH_REQUEST_SIGNIN',
    AUTH_REQUEST_SIGNUP: 'AUTH_REQUEST_SIGNUP',
    AUTH_REQUEST_SIGNOUT: 'AUTH_REQUEST_SIGNOUT',
    AUTH_SYNC: 'AUTH_SYNC',
    INITIAL_AUTH:'INITIAL_AUTH',
    SIGN_OUT: 'SIGN_OUT',
    SYNC_USER: 'SYNC_USER'
}
export const Channel = {
    ATTACH_REVIEWS_LISTENER:'ATTACH_REVIEWS_LISTENER',
    ATTACH_LIKES_LISTENER: 'ATTACH_LIKES_LISTENER',
    DETACH_REVIEWS_LISTENER: 'DETACH_REVIEWS_LISTENER',
    DETACH_LIKES_LISTENER: 'DETACH_LIKES_LISTENER'
}
export const ErrorHandle = {
    ERROR_WHEN_AUTH: 'ERROR_WHEN_AUTH',
    ERROR_WHEN_SEARCHING_MOVIE: 'ERROR_WHEN_SEARCHING_MOVIE',
    ERROR_WHEN_SEARCHING_MOVIE_DETAIL: 'ERROR_WHEN_SEARCHING_MOVIE_DETAIL',
    OFF_ERROR_WHEN_SEARCHING_MOVIE: 'OFF_ERROR_WHEN_SEARCHING_MOVIE',
    OFF_ERROR_WHEN_SEARCHING_MOVIE_DETAIL: 'OFF_ERROR_WHEN_SEARCHING_MOVIE_DETAIL'
}
export const Modal = {
    IS_SEARCHING: 'IS_SEARCHING',
    IS_NOT_SEARCHING: 'IS_NOT_SEARCHING',
    IS_QUERYING: 'IS_QUERYING',
    IS_NOT_QUERYING: 'IS_NOT_QUERYING'
}
export const Movie = {
    CANCEL_REQUEST_MOVIE_BY_TITLE:'CANCEL_REQUEST_MOVIE_BY_TITLE',
    CANCEL_REQUEST_MOVIE_BY_ID: 'CANCEL_REQUEST_MOVIE_BY_ID',
    REQUEST_MOVIE_BY_TITLE: 'REQUEST_MOVIE_BY_TITLE',
    REQUEST_MOVIE_BY_ID: 'REQUEST_MOVIE_BY_ID'
}
export const MovieDetail = {
    SET_MOVIE_DETAIL: 'SET_MOVIE_DETAIL',
    SET_MOVIE_DETAIL_REPLIES:'SET_MOVIE_DETAIL_REPLIES'
}
export const MovieList = {
    ADD_MOVIE_LIST: 'ADD_MOVIE_LIST',
    SET_MOVIE_LIST: 'SET_MOVIE_LIST'
}
export const Reviews = {
    INITIAL_LOAD: 'INITIAL_LOAD',
    REVIEW_ADDED: 'REVIEW_ADDED',
    REVIEW_UPDATED: 'REVIEW_UPDATED',
    REVIEW_DELETED: 'REVIEW_DELETED',
    REVIEW_UPLOAD: 'REVIEW_UPLOAD',
    REVIEW_UPDATE: 'REVIEW_UPDATE',
    REVIEW_REMOVE: 'REVIEW_REMOVE'
}
export const Toast = {
    TOAST_ON: 'TOAST_ON',
    TOAST_OFF: 'TOAST_OFF'
}